version: "2"
services:
  go:
    image: golang
    networks:
      - back
    expose:
      - "9003"
    ports:
      - "9001:9003"
  arango:
    image: arangodb:3.4.7
    ports:
      - "8529:8529"
    networks:
      back:
        aliases:
          - "timedEvent.db.ivanmeca.com.br"
    volumes:
      - ./docker-data/arangodb:/var/lib/arangodb
    environment:
      ARANGO_ROOT_PASSWORD: "rootpass"
      ARANGO_STORAGE_ENGINE: rocksdb
  rabbitmq:
    image: rabbitmq:management
    networks:
      back:
        aliases:
          - "timedEvent.queue.ivanmeca.com.br"
    expose:
      - "15672"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: randomUser
      RABBITMQ_DEFAULT_PASS: randomPass
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./docker-data/rabbitmq/data:/var/lib/rabbitmq

networks:
  back: