version: "2"
services:
  go:
    image: golang
    networks:
      - back
    expose:
      - "9003"
    ports:
      - "9001:9003"
    volumes:
      - ../:/go/src/github.com/ivanmeca/timedQueueService

  rabbitmq:
    image: rabbitmq:management
    networks:
      back:
        aliases:
          - "queue.interno.ivanmeca.com.br"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: testuser
      RABBITMQ_DEFAULT_PASS: testPass
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./docker-data/rabbitmq/data:/var/lib/rabbitmq
  mongo:
    image: mongo
    networks:
      back:
        aliases:
          - "db.interno.ivanmeca.com.br"
    expose:
      - "27017"
    ports:
      - "27017:27017"
  #    restart: always
  #    environment:
  #      MONGO_INITDB_ROOT_USERNAME: root
  #      MONGO_INITDB_ROOT_PASSWORD: example-
networks:
  back: