version: "2"
services:
  go:
    image: golang
    links:
      - "rabbitmq:srvqueue.ivanmeca.com.br"
    expose:
      - "9003"
    ports:
      - "9001:9003"
    volumes:
      - ../:/go/src/github.com/ivanmeca/timedQueueService

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: testuser
      RABBITMQ_DEFAULT_PASS: testPass
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
