version: "2"
services:
  go:
    image: golang
    networks:
      - back
    expose:
      - "9003"
    ports:
      - "9001:9003"
    volumes:
      - ../:/go/src/github.com/ivanmeca/timedQueueService

  rabbitmq:
    image: rabbitmq:management
    networks:
      back:
        aliases:
          - "queue.interno.ivanmeca.com.br"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: testuser
      RABBITMQ_DEFAULT_PASS: testPass
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./docker-data/rabbitmq/data:/var/lib/rabbitmq
  arangodb:
    image: arangodb:3.4.0
    networks:
      back:
        aliases:
          - "db.interno.ivanmeca.com.br"
    ports:
      - 8529:8529
    volumes:
      - ./docker-data/arango/:/var/lib/arangodb-apps/_db
    environment:
      - ARANGO_NO_AUTH=1
networks:
  back: